---
- name: ELK Deployment Playbook
  hosts: webservers
  become: true
  tasks:

  - name: Install docker.io
    apt:
      update_cache: yes
      name: docker.io
      state: present

  - name: Install python3-pip
    apt:
      name: python3-pip
      state: present

  - name: Install docker
    pip:
      name: docker
      state: present

  - name: Install docker container
    docker_container:
      name: dvwa
      image: cyberxsecurity/dvwa
      state: started
      restart_policy: always
      published_ports: 80:80

  - name: enable Docker service
    systemd:
      name: docker
      enabled: yes

  - name: Download Filebeat
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

  - name: Install Filebeat
    command: dpkg -i filebeat-7.4.0-amd64.deb

  - name: Copy Config File
    copy:
      src: /etc/ansible/files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

  - name: Command 1
    command: filebeat modules enable system

  - name: Command 2
    command: filebeat setup

  - name: Command 3
    command: service filebeat start

  - name: Enable Filebeat Service
    systemd:
      name: filebeat
      enabled: yes

  - name: Download Metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

  - name: Install Metricbeat
    command: dpkg -i metricbeat-7.4.0-amd64.deb

  - name: Copy Config File
    copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: Command 1
    command: metricbeat modules enable docker

  - name: Command 2
    command: metricbeat setup

  - name: Command 3
    command: service metricbeat start

  - name: Enable Metricbeat Service
    systemd:
      name: metricbeat
      enabled: yes