

  - name: Download Metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

  - name: Install Metricbeat
    command: dpkg -i metricbeat-7.4.0-amd64.deb

  - name: Copy Config File
    copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: Command 1
    command: metricbeat modules enable docker

  - name: Command 2
    command: metricbeat setup

  - name: Command 3
    command: service metricbeat start

  - name: Enable Metricbeat Service
    systemd:
      name: metricbeat
      enabled: yes